# Generated by Django 3.1.4 on 2020-12-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAcount',
            fields=[
                ('twitter_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idol')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(db_index=True)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.IntegerField()),
                ('retweet_count', models.IntegerField()),
                ('retweeted', models.BooleanField(default=False)),
                ('acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.twitteracount')),
                ('hashtags', models.ManyToManyField(related_name='tweets', to='core.HashTag')),
                ('pictures', models.ManyToManyField(related_name='tweets', to='core.Picture')),
            ],
        ),
    ]
